AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
   - "spec/*"

Metrics/MethodLength:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 19
